openapi: 3.0.1
info:
  title: EmployeeAPI
  description: API Definition of EmployeeAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/employees
paths:
  /employees:
    get:
      responses:
        default:
          description: Default response
