openapi: 3.0.1
info:
  title: JSONtoXMLConverterAPI
  description: API Definition of JSONtoXMLConverterAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/convert
paths:
  /jsonToXml:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
