openapi: 3.0.1
info:
  title: OlaBrasilAPI
  description: API Definition of OlaBrasilAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/olaBrasil
paths:
  /sayHello:
    get:
      responses:
        default:
          description: Default response
