openapi: 3.0.1
info:
  title: PetstoreAPI
  description: API Definition of PetstoreAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/petstore
paths:
  /pet:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
  /pet/findByStatus:
    get:
      parameters:
      - name: status
        in: query
        schema:
          type: string
      responses:
        default:
          description: Default response
  /pet/{petId}:
    get:
      parameters:
      - name: petId
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
    delete:
      parameters:
      - name: petId
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
