openapi: 3.0.1
info:
  title: PhoneVerificationAPI
  description: API Definition of PhoneVerificationAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/phoneVerify
paths:
  /checkPhoneNumber:
    get:
      parameters:
      - name: PhoneNumber
        in: query
        schema:
          type: string
      - name: LicenseKey
        in: query
        schema:
          type: string
      responses:
        default:
          description: Default response
