openapi: 3.0.1
info:
  title: CDYNEPhoneVerificationAPI
  description: API Definition of CDYNEPhoneVerificationAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/phoneVerification
paths:
  /checkPhoneNumber:
    get:
      parameters:
      - name: phoneNumber
        in: query
        schema:
          type: string
      - name: licenseKey
        in: query
        schema:
          type: string
      responses:
        default:
          description: Default response
